### ISSUE TITLE
Create registration page with details

### ISSUE THREAD

**Issue by anya1609** [ita-social-projects/Fragments-back-end#16]
**As a** user **I want to** have a personal account on the website **so that** I had more rights and could join initiatives

**Description**
This is the initial user story for creating data model for the user in the system. The goal will be that user can register with facebook , initial details are populated from there and then user can specify more details on the website itself

### Acceptance Criteria
1. Create a page for user registration details

2. The page should have following fields:
2.1.  "Е-мейл" - user email, text field with email format (@ and dot) , cannot be empty , and email should be unique identifier of a user
2.2. "Імя" - user first name, text field that should have only letters and special character allowed "'" , max 100 symbols , required, may not be unique
2.3.  "Прізвище" - user last name, text field that should have only letters and special character allowed "'" , max 100 symbols , required, may not be unique
2.4. “Фото” is required 
2.5.  “День народження” is required and consists of three sub-fields put in a line. The sub-fields are represented by search fields with dropdown menu:
  2.5.1. “день” - dropdown menu contains numbers from 1 to 31 - when user selects number, the system displays it in the sub-field "день";
  2.5.2. “місяць” - dropdown menu contains the names of 12 months: "Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень" - when user selects month, the system displays it in the sub-field "місяць";
  2.5.3. “рік” - dropdown menu contains numbers from 1900 to 2022 - - when user selects number, the system displays it in the sub-field "рік". 

4. The page should have a button "Зберегти" 
 3.1. button should be disabled until all required fields are specified 
 3.2. button should have a tooltip when disabled "Вкажіть повне ім'я і електрону адресу"
 3.3. button should become enabled once required fields are specified
5.  When user selects "Зберегти" button THEN
5.1. User data should be saved to database
5.2.  User should see message "Дані збережено" when db saves data
5.3.  User should see message "Сталась помилка" when data is not saved for some reason

**Epic link**
Epic #15  [Epic](https://jira.softserve.academy/browse/15)

**Comment by Mark14444** [comment]
Create registration page with details
