### ISSUE TITLE
Create a account details registration page

### ISSUE THREAD

**Issue by KhrystynaSuliy** [ita-social-projects/Fragments-back-end#18]
As a user I want to populate additional data in account details registration page so that site community knew about me more.

**PRECONDITIONS**

1. The user started account creation on a page for user registration details https://github.com/ita-social-projects/Fragments-back-end/issues/16
2. The user undertook registration via Facebook https://github.com/ita-social-projects/Fragments-back-end/issues/17
3. The user is redirected from Facebook to the website's account details registration page in order to specify more details.
4. The following fields are populated automatically via Facebook:
- “Фото”
- “Ім’я та прізвище”
- "e-mail"

**ACCEPTANCE CRITERIA**

1. Create an account details registration page to specify user registration details.

2. Add following fields to the registration form: 
2.1. Label at the top "Вітаємо! Для завершення реєстрації у Спільності дозвольте нам дізнатися про Вас більше:".
2.2. checkbox “представник влади” is not required , unchecked by default
2.3. checkbox “представник ЗВО” is not required, unchecked by default.    
2.4. text field “Чим можу бути корисним” is not required. special characters allowed, max. 500 characters. There is a tooltip button located outside the field near the right upper corner. The tooltip button is represented by a dialogue bubble with a question mark (?) inside. 
2.5. text field “Мої інтереси” is not required. special characters allowed, max. 500 characters. There is a tooltip button located outside the field near the right upper corner. The tooltip button is represented by a dialogue bubble with a question mark (?) inside. 
2.6. Additional communication channel consists of three sub-fields put in a line:
 2.6.1. an add button - a box with a plus sign (+) inside - the button is disabled until user populates "канал зв'язку" and "деталі";
 2.6.2. a delete button - a trash bin symbol (🗑) - the button is disabled until user populates "канал зв'язку" and "деталі"
 2.6.3.  "канал зв'язку" - a search field with a dropdown menu. The dropdown menu has the following:  viber, telegram, messenger, sms. The user may select only 1 communication channel at a time; 
 2.6.4. "номер телефону або username" - details of user's communication channel - text field, special characters allowed, max. 100 characters, should be unique identifier of a user;

3. When user selects button “Зберегти”, the system:
3.1. save new/updated data in the database
3.2. shows relevant notification: “Дякуємо! Ваші дані збережено”
3.3. show notification "Сталася помилка" when data is no saved for some reason.
  
epic link #15

**Comment by Dammy99** [comment]
@anya1609 2.2 , 2.3 : one of radiobuttons should be selected. What other type of user can be there ?

**Comment by KhrystynaSuliy** [comment]
updated the ticket as agreed: radiobutton changed to checkbox.

**Comment by Dammy99** [comment]
@KhrystynaSuliy 
2.6.2: Need a trash bin symbol picture
Asking you to pay attention to the design of this story
