### ISSUE TITLE
Allow user to Sign in the website

### ISSUE THREAD

**Issue by MiaSKY** [ita-social-projects/Fragments-back-end#49]
As a user, I want to sign in to the website so that I could access my personal account and join initiatives.
 
**Description**
This is the user story for creating data model for the user in the system. The goal will be that user can sign in their profile anytime. User can sign in to the website with Google and Facebook [Фрагменти – Figma](https://www.figma.com/file/XcIVcHeE8soc96iX4UGVkg/%D0%A4%D1%80%D0%B0%D0%B3%D0%BC%D0%B5%D0%BD%D1%82%D0%B8?node-id=6%3A162)

**Preconditions**

1. User has already created an account with Google or Facebook
2. Button for signing in is implemented on the Header of the page, according to the mock-up.

**Acceptance criteria**

1. When the user clicks “Увійти” button on the header of the page then user should see the pop-up window with options to select “Sign in with Google” or “Sign in with Facebook” 
2. When user selects “Sign in with Google” “Увійти через Google” then user should be redirected to the profile page or the initial page as registered user.
3. When the user selects Sign in with Facebook “Увійти через Facebook” then user should be redirected to the profile page or the initial page as registered user
4. User’s photo and name should be displayed on the header of the page, according to mockup
- Application should display photo that was added manually, If there is a photo saved manually
- If there is no photo added manually, it will be displayed from Facebook or Google account.
5. The system should not sign out until the user logs themselves out. The system should remember user’s domain

Epic link #15 

Subtasks: https://github.com/ita-social-projects/Fragments-back-end/issues/53

**Comment by Vladyslavko36** [comment]
Completed: 24 hours
