### ISSUE TITLE
Protect main branches of  Fragments-back-end and  Fragments-front-end repositories

### ISSUE THREAD

**Issue by nrevutska** [ita-social-projects/Fragments-back-end#6]
Protect main branches of  Fragments-back-end and  Fragments-front-end repositories and enforce contribution rules on them
Enable the following settings:

- Collaborators cannot force push to a protected branch or delete the branch
- Require pull request reviews before merging (2 at least)
- Allow merge if all Sonar tests are passed
- Allow merge if all Unit tests are passed
- Allow merge if all comments in pull request are approved

**Comment by Vladyslavko36** [comment]
Estimation: 3 hours

**Comment by Vladyslavko36** [comment]
Done: 3 hours
