### ISSUE TITLE
Admin. Search users by keywords

### ISSUE THREAD

**Issue by anya1609** [ita-social-projects/Fragments-back-end#72]
As an administrator, I want to search users by keywords so that I could find users faster, which corresponds to my needs

**Description**
This user story is created to enable administrators to find users by keywords and make needed actions with the users profiles.

**Preconditions**

1. All the functionality of a registered user is accessible to the administrator
2. Admin is registered and signed in

### Acceptance Criteria
1. Create a search bar ‘Пошук’ on the admin starting (home) page
2. An admin can search users in the "Пошук" table by using a search field at the upper left corner of the web page.
2.1. Search input field contains a placeholder: "Пошук" 
2.2. When admin enters the first character, text in the input field disappears and appears again when the input field is empty.
2.3. Search field activates once admin types at least 1 letter/ 1 number/ 1 reserved character
2.4. System starts automatic search after the 3rd characters
2.5. Search field allows maximum 50 characters 
2.6. Search is allowed by entering any characters: alphabetic characters, a dot, a space, apostrophe and hyphen
2.7. Search is performed by all text fields, except columns ‘Дата останньої активності’, ‘Дата реєстрації’
3. All of the entries present in the search criteria that are separated with the space should be present in the results set
5. When admin clicks the button search ‘Пошук’ after typing input in the search field THEN:

- the found users should be shown as a list of maximum 25 users on the first page
- pagination should be supported AND a total number of found items should be shown
- search results should correspond to the items from the table that contain data that matches the search input
- search results should be displayed in an alphabet order by default 

6. If matches were not found System should display the empty table with the message: "Користувачів за критерієм пошуку не знайдено." 
7. Admin can clear a search field:

-  by selecting the input text and tapping the button with the delete function
-  by clicking on a close icon in the search field

8. If any filtering and/or sorting parameters were applied before the search was used, the search outputs should be ordered by the set filtering and/or sorting.

**Epic link**
https://github.com/ita-social-projects/Fragments-back-end/issues/66 

**Labels to be added**
"story"

### Tasks 
1. - [ ] sample task.

**Comment by Dammy99** [comment]
Estimated: 12 hours

**Comment by Dammy99** [comment]
Completed: 24 hours
