### ISSUE TITLE
Allow to display notification marker in real-time

### ISSUE THREAD

**Issue by KhrystynaSuliy** [ita-social-projects/Fragments-back-end#74]
**As a** user **I want** maker over the bell icon to signal about new notification in real-time **so that** I stay updated about the latest events. 

**Description**
This is one of the user stories for creating a registered user’s profile. The goal is that registered user will be informed about new notifications in their notification list in real-time.

**Preconditions**
1. User is registered.
3. User has all notifications read.

### Acceptance Criteria
1. There is a bell-icon in the Header https://github.com/ita-social-projects/Fragments-back-end/issues/59 

2. When a new notification reaches the inbox of a user, THEN 
- user can see a notification marker - small yellow circle - by the bell-icon in real-time

3. When user clicks on the bell-icon, THEN:
- user is redirected to ‘My notification’ page https://github.com/ita-social-projects/Fragments-back-end/issues/59 with the list of all notifications by default;
- the latest notification is marked and placed at the top of the notification list by default. 

4. When user is on the ‘My notification’ page and selects an unread notification to read it, THEN notification marker disappears.

5. If the number of unread notifications is > 1, THEN:
- notification marker remains until user reads all unread notifications; 
- notification marker disappears when user reads all unread notifications.  

**Epic link**
Epic #51 

Mockup 
https://www.figma.com/file/XcIVcHeE8soc96iX4UGVkg/%D0%A4%D1%80%D0%B0%D0%B3%D0%BC%D0%B5%D0%BD%D1%82%D0%B8?node-id=1069%3A7584
<img width="1033" alt="Screenshot 2022-07-12 at 18 37 16" src="https://user-images.githubusercontent.com/102864740/178531699-e4609e0a-02f2-46fa-ac6e-a903456f43ec.png">

**Comment by Vladyslavko36** [comment]
Completed: 18 hours
