### ISSUE TITLE
Use the ES Lint tool

### ISSUE THREAD

**Issue by nrevutska** [ita-social-projects/Fragments-back-end#8]
Use the ES Lint tool and ability to enforce predefined rules for every pull request to the Fragments-front-end repository

**Comment by shon327** [comment]
Estimation 6 hours

**Comment by AlexPokatilov** [comment]
[https://github.com/ita-social-projects/Fragments-front-end/issues/24](url)
[https://github.com/ita-social-projects/Fragments-front-end/pull/25](url)
Added to subtask and done
